name: CMake-Binaries

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "**.c", "**.h" ]

env:
  REPO: "dangduc/fzf-native"
  BRANCH: "cmake"

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      run: cmake -B ${{github.workspace}}/build -DCMAKE_C_FLAGS='-O3 -march=native'

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build

    - name: Commit
      continue-on-error: false
      run: |
        git pull
        git add .
        git commit -m "Update module binary ${{ matrix.os }}"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        repository: ${{ env.REPO }}
        branch: ${{ env.BRANCH }}
        # https://github.com/Azure/actions-workflow-samples/blob/master/assets/create-secrets-for-GitHub-workflows.md
        github_token: ${{ secrets.GITHUB_TOKEN }}